import type { Metadata } from "next";
import { Kantumruy_Pro } from "next/font/google";

import "./globals.css";
import { Toaster } from "sonner";
import { AuthGuard } from "@/components/guards/auth-guard";
import { Loading } from "@/components/customs/loading";

const kantumruy = Kantumruy_Pro({
  subsets: ["latin"],
  variable: "--font-kantumruy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={kantumruy.className}
      >
        {/* <AuthGuard> */}
          {children}
          <Loading />
        {/* </AuthGuard> */}

        <Toaster
          richColors
          position="top-right"
        />
      </body>
    </html>
  );
}